package:
  name: mesh2volume
  version: "0.0.1"
source:
  path: ../python
build:
  number: 0
  binary_relocation: true
  script:
    - python -m pip install . -vvv
requirements:
  build: 
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make # [not win]
    - openvdb
  host:
    - boost-cpp
    - tbb-devel
    - blosc
    - zlib
    - jemalloc # [not win]
    - openvdb
    - eigen
    - python
    - pip
    - pybind11
  run:
    - openvdb
    - python
